site_name: Understanding crew ai
theme:
  name: material

plugins:
  - search
  - mermaid2
  - mkdocstrings:
      default_handler: python

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom

nav:
  - Home: index.md
  - Agents: agents.md
  - Tasks: tasks.md
  - Crew: crew.md

extra:
  include_code: ['src']
